import {
  ShieldCheck,
  Flag,
  PackageCheck,
  Truck,
  BookOpen,
  ReceiptText,
  ListTree,
  ClipboardList,
  Clock,
  TrendingUp,
  Plus,
  Search,
  X,
  Check,
  CheckCircle2,
  AlertCircle,
  Info,
  RefreshCw,
  Download,
  DownloadCloud,
  LogOut,
  Users,
  KeyRound,
  Mail,
  Copy,
  Pencil,
  ChevronDown,
  UserPlus,
  Trash2,
  Rocket,
  Building2,
  Loader2,
  ArrowRight,
  Send,
  UserCog,
  CalendarClock,
  Ban,
  RotateCcw,
  Sparkles,
  LayoutDashboard,
  LayoutGrid,
  ChevronsUpDown,
  ChevronsDownUp,
  MousePointerClick,
  Eye,
  EyeOff,
  Minus,
  Bell,
  Settings,
  Zap,
  ArrowUpRight,
  Activity,
  Wallet,
  BarChart3,
  LineChart,
  MapPin,
  Play,
  Square,
  Moon,
  Timer,
  ChevronRight,
  ArrowLeft,
  FileSpreadsheet,
  CircleDot,
  CalendarDays,
  CalendarPlus,
  Boxes,
  Package,
  PackagePlus,
  DollarSign,
  ShoppingCart,
  Tag,
  Layers,
  AlertTriangle,
  Warehouse,
  TrendingDown,
  Maximize2,
  ImagePlus,
  PackageMinus,
  Repeat,
  ScanBarcode,
  ScanLine,
  Camera,
  CameraOff,
  Keyboard,
  Undo2,
  History,
  Percent,
  CalendarSearch,
  CreditCard,
  // --- RM Cardz Shipping workspace (shell / Upload / Orders) ---
  UploadCloud,
  FileUp,
  ListChecks,
  Siren,
  SquareStack,
  Gift,
  Megaphone,
  PauseCircle,
  Crown,
  Sticker,
  StickyNote,
  Hash,
  ExternalLink,
  Wand2,
  Link,
  Lock,
  ArrowUp,
  ArrowDown,
  Eraser,
  ChevronUp,
  // --- RM Cardz Shipping workspace (Checker / Shipping / History) ---
  Circle,
  CheckCheck,
  ClipboardCheck,
  ClipboardPaste,
  PackageOpen,
  Link2,
  Link2Off,
  Archive,
  Save,
  FileDown,
  FileCheck,
  FileText,
  FileX,
  User,
  Scale,
  // --- History calendar ---
  ChevronLeft,
  CalendarRange,
  Flame,
  // --- Break assignments ---
  UserCheck,
  UserMinus,
  // --- Case / box / pack unit economics ---
  Calculator,
  // --- The owner board's status tiles ---
  Radio,
  Inbox,
  CheckSquare,
  // --- Employee performance ---
  Gauge,
  type LucideIcon
} from 'lucide-react'

const MAP: Record<string, LucideIcon> = {
  ShieldCheck,
  Flag,
  PackageCheck,
  Truck,
  BookOpen,
  ReceiptText,
  ListTree,
  ClipboardList,
  Clock,
  TrendingUp,
  Plus,
  Search,
  X,
  Check,
  CheckCircle2,
  AlertCircle,
  Info,
  RefreshCw,
  Download,
  DownloadCloud,
  LogOut,
  Users,
  KeyRound,
  Mail,
  Copy,
  Pencil,
  ChevronDown,
  UserPlus,
  Trash2,
  Rocket,
  Building2,
  Loader2,
  ArrowRight,
  Send,
  UserCog,
  CalendarClock,
  Ban,
  RotateCcw,
  Sparkles,
  LayoutDashboard,
  LayoutGrid,
  ChevronsUpDown,
  ChevronsDownUp,
  MousePointerClick,
  Eye,
  EyeOff,
  Minus,
  Bell,
  Settings,
  Zap,
  ArrowUpRight,
  Activity,
  Wallet,
  BarChart3,
  LineChart,
  MapPin,
  Play,
  Square,
  Moon,
  Timer,
  ChevronRight,
  ArrowLeft,
  FileSpreadsheet,
  CircleDot,
  CalendarDays,
  CalendarPlus,
  Boxes,
  Package,
  PackagePlus,
  DollarSign,
  ShoppingCart,
  Tag,
  Layers,
  AlertTriangle,
  Warehouse,
  TrendingDown,
  Maximize2,
  ImagePlus,
  PackageMinus,
  Repeat,
  ScanBarcode,
  ScanLine,
  Camera,
  CameraOff,
  Keyboard,
  Undo2,
  History,
  Percent,
  CalendarSearch,
  CreditCard,
  // --- RM Cardz Shipping workspace (shell / Upload / Orders) ---
  UploadCloud,
  FileUp,
  ListChecks,
  Siren,
  SquareStack,
  Gift,
  Megaphone,
  PauseCircle,
  Crown,
  Sticker,
  StickyNote,
  Hash,
  ExternalLink,
  Wand2,
  Link,
  Lock,
  ArrowUp,
  ArrowDown,
  Eraser,
  ChevronUp,
  // --- RM Cardz Shipping workspace (Checker / Shipping / History) ---
  Circle,
  CheckCheck,
  ClipboardCheck,
  ClipboardPaste,
  PackageOpen,
  Link2,
  Link2Off,
  Archive,
  Save,
  FileDown,
  FileCheck,
  FileText,
  FileX,
  User,
  Scale,
  // --- History calendar ---
  ChevronLeft,
  CalendarRange,
  Flame,
  // --- Break assignments ---
  UserCheck,
  UserMinus,
  // --- Case / box / pack unit economics ---
  Calculator,
  // --- The owner board's status tiles ---
  Radio,
  Inbox,
  CheckSquare,
  // --- Employee performance ---
  Gauge
}

export function Icon({
  name,
  size = 18,
  className,
  strokeWidth = 2,
  title
}: {
  name: string
  size?: number
  className?: string
  strokeWidth?: number
  /**
   * Hover text, as an SVG <title> CHILD rather than a title attribute — SVG has
   * no title attribute, so the attribute form draws no tooltip. lucide renders
   * whatever children it is given inside the <svg>, which keeps the icon a
   * direct child of its container and leaves every `> svg` rule intact.
   */
  title?: string
}): JSX.Element | null {
  const Cmp = MAP[name]
  if (!Cmp) return null
  return (
    <Cmp size={size} className={className} strokeWidth={strokeWidth}>
      {title ? <title key="t">{title}</title> : null}
    </Cmp>
  )
}
